name: DB-insertion

on:
  push:
    branches: ["master"]
    paths:
      - "db-insert/csv/**"
  pull_request:
    branches: ["master"]
    paths:
      - "db-insert/csv/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd db-insert
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python
        env:
          DB_IP_ADDR: ${{ secrets.DB_IP_ADDR }}
        run: |
          cd db-insert
          echo $DB_IP_ADDR
          python csv_reader.py >> output.txt
          cat output.txt
      - name: Commit & Push
        run: |
          cd db-insert
          git config user.name "dntjd1097"
          git config user.email "dntjd1097@gmail.com"
          git add -A .
          git commit -m "remove .csv"
          git push
